apiVersion: apps/v1
kind: Deployment
metadata:
  name: cuebot-app
spec:
  selector:
    matchLabels:
      app: cuebot-app
  replicas: 1
  template:
    metadata:
      labels:
        app: cuebot-app
    spec:
      containers:
        - name: cuebot-app
          image: registry.gitlab-ncsa.ubisoft.org/helix/poc/opencue/opencue:1.14.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8443
          resources:
            requests:
              memory: "6Gi"
              cpu: "1000m"
            limits:
              memory: "16Gi"
              cpu: "4000m"
          env:
            - name: CUE_FRAME_LOG_DIR
              value: \\ubisoft.org\mtlstudio\Helix\tools\farm\opencue.prod
            - name: CUEBOT_DB_URL
              valueFrom:
                secretKeyRef:
                  name: cuebot-secrets
                  key: db-url
            - name: CUEBOT_DB_USER
              valueFrom:
                secretKeyRef:
                  name: cuebot-secrets
                  key: db-username
            - name: CUEBOT_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cuebot-secrets
                  key: db-password
      imagePullSecrets:
        - name: gitlab-docker-registry-compiltwine

---

apiVersion: v1
kind: Service
metadata:
  name: cuebot-service
  annotations:
    service.beta.kubernetes.io/linode-loadbalancer-throttle: "4"
spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: 8443
      targetPort: 8443
      protocol: TCP
  selector:
    app: cuebot-app
